### ISSUE TITLE
lossy type 2 for 12 bit

### ISSUE THREAD

**Issue by HartwigThomas** [6by9/dcraw#1]
in lines 1188/1190 there are two Huffmann tree tables.
They have the same lengths but different leaf-values.
The first has 13 leaf values, the secand has 14 leaf values.(The latter corresponds to my manual construction of the Huffmann tree)
Two trees with the same lengths must have the same number of leaves!
Doesn't the make_decode read a value beyond the last element in the array? Does the value, it finds there, make any sense?
So, what is the correct missing last value of the first tree?

**Comment by 6by9** [comment]
This branch is based on dcraw from http://www.cybercom.net/~dcoffin/dcraw/ - it only adds handling for the Raspberry Pi cameras.
I'm afraid I have no information on details of the Nikon decoding code. You'll need to refer any issues on that back to Dave Coffin.

**Comment by 6by9** [comment]
Closing as this is an issue with the upstream dcraw that needs to be addressed there.
