### ISSUE TITLE
cant install dcraw.c,  libjpeg.so.62 may conflict with libjpeg.so.8

### ISSUE THREAD

**Issue by xiao-wang007** [6by9/dcraw#2]
Hi, the modified version of dcraw.c does not seem to be installed on my machine. 

I've tried several times.
it always gives me the following warning:

warning: libjpeg.so.62, needed by /usr/lib/gcc/arm-linux-gnueabihf/6/../../../arm-linux-gnueabihf/libjasper.so, may conflict with libjpeg.so.8

tried to use dcraw after done with ./buildme, it says command not found

**Comment by 6by9** [comment]
What's your machine? A Pi or some other random Linux box?
I've got no such errors on a fully Pi running Stretch. Sorry, but I'm not going to try supporting all sorts of random Linux distros.

edit: Take it back - ld has thrown an error.

**Comment by xiao-wang007** [comment]
I'm using pi 3 B+ with Raspbian Stretch with desktop.  the one downloaded from raspberry pi official website.
Is there a way to deal with this warning?  try reinstall the OS?

Thanks for your prompt reply!

**Comment by xiao-wang007** [comment]
Just a check. Do I need to install the original Dcraw first. Then install your modified version as instructed??

Thanks

**Comment by 6by9** [comment]
> Is there a way to deal with this warning? try reinstall the OS?

I suspect something has been updated in Raspbian and has a broken dependency. I'll have a look.

> Just a check. Do I need to install the original Dcraw first. 

No.

**Comment by 6by9** [comment]
Investigated more. It is a build warning only. The build completes and I have a dcraw executable file in the current directory.
The script does NOT install dcraw, therefore you need to run as ./dcraw as Linux never puts the current directory in the search path for executables.

**Comment by xiao-wang007** [comment]
Thats good news! My project is depending on this! Will have a try later when I get back! 


Thank you so much!

**Comment by xiao-wang007** [comment]
Thank you! it worked perfectly!
