### ISSUE TITLE
./buildme runs error.

### ISSUE THREAD

**Issue by Jackjiang313** [6by9/dcraw#5]
dcraw.c:77:10: fatal error: jasper/jsaper.h: No such file or directory

compilation terminated

**Comment by 6by9** [comment]
From the README:
```
Build instructions:

sudo apt-get install libjasper-dev libjpeg8-dev gettext liblcms2-dev
./buildme
```
Did you do that first step to install the dependencies?

**Comment by Jackjiang313** [comment]
> From the README:
> 
> ```
> Build instructions:
> 
> sudo apt-get install libjasper-dev libjpeg8-dev gettext liblcms2-dev
> ./buildme
> ```
> 
> Did you do that first step to install the dependencies?

I have solved it. Thank you a lot.
