### ISSUE TITLE
Extract 10bit raw image as a tiff image

### ISSUE THREAD

**Issue by arpit15** [6by9/dcraw#6]
I dumped the jpeg+raw image from RPi v1 camera. After I process the images using 
`dcraw -v -4 -H 0 -W -w -q 3 -T -p embed -o sRGB myimage.jpeg`, I obtain a 16bit tiff image with the maximum value being `2^16`. I don't understand how and where does the conversion from 10bit to 16bit image takes place inside the code.  Can you kindly let me know how to dump demosaiced images that have maximum values around `2^10`?

**Comment by 6by9** [comment]
https://github.com/6by9/dcraw/blob/master/dcraw.c#L2010 defines a maximum pixel value of 0x3ff (10 bits). (If you look in load_raw12 then the max is 0xfff for 12bits, etc).

It looks like [scale_colors](https://github.com/6by9/dcraw/blob/master/dcraw.c#L3619) is then scaling by that value when it computes ```scale_mul[]```.

Set maximum to 0xffff and I suspect you'll disable the scaling.

**Comment by arpit15** [comment]
Thanks for your reply. Replacing the maximum with `0xffff` doesn't disable the scaling as the `pre_mul[]` could be greater than 1 and then the clipping would only limit b/w `0` and `65535`. Instead of changing dcraw, currently, I am multiplying the images after tiff images are dumped on disk. Do you have a better suggestion?

**Comment by 6by9** [comment]
TBH I don't really have much input in how dcraw is processing the data.
I added the relevant parsing for the Pi raws, but all the other code is vanilla dcraw.

Looking at the help text:
```

Raw photo decoder "dcraw" v9.27
by Dave Coffin, dcoffin a cybercom o net

Usage:  ./dcraw [OPTION]... [FILE]...

-v        Print verbose messages
-c        Write image data to standard output
-e        Extract embedded thumbnail image
-i        Identify files without decoding them
-i -v     Identify files and show metadata
-z        Change file dates to camera timestamp
-w        Use camera white balance, if possible
-a        Average the whole image for white balance
-A <x y w h> Average a grey box for white balance
-r <r g b g> Set custom white balance
+M/-M     Use/don't use an embedded color matrix
-C <r b>  Correct chromatic aberration
-P <file> Fix the dead pixels listed in this file
-K <file> Subtract dark frame (16-bit raw PGM)
-k <num>  Set the darkness level
-S <num>  Set the saturation level
-n <num>  Set threshold for wavelet denoising
-H [0-9]  Highlight mode (0=clip, 1=unclip, 2=blend, 3+=rebuild)
-t [0-7]  Flip image (0=none, 3=180, 5=90CCW, 6=90CW)
-o [0-6]  Output colorspace (raw,sRGB,Adobe,Wide,ProPhoto,XYZ,ACES)
-o <file> Apply output ICC profile from file
-p <file> Apply camera ICC profile from file or "embed"
-d        Document mode (no color, no interpolation)
-D        Document mode without scaling (totally raw)
-j        Don't stretch or rotate raw pixels
-W        Don't automatically brighten the image
-b <num>  Adjust brightness (default = 1.0)
-g <p ts> Set custom gamma curve (default = 2.222 4.5)
-q [0-3]  Set the interpolation quality
-h        Half-size color image (twice as fast as "-q 0")
-f        Interpolate RGGB as four colors
-m <num>  Apply a 3x3 median filter to R-G and B-G
-s [0..N-1] Select one raw image or "all" from each file
-6        Write 16-bit instead of 8-bit
-4        Linear 16-bit, same as "-6 -W -g 1 1"
-T        Write TIFF instead of PPM
```
-W may do what you want.

**Comment by arpit15** [comment]
I am passing `-W` flag. However, it is still leading to the scaling. I will close this issue as there is no more information available that would allow me to output a 10bit image after processing using dcraw.
