### ISSUE TITLE
libjpeg8-dev no longer available

### ISSUE THREAD

**Issue by kyleboddy** [6by9/dcraw#7]
`sudo apt-get install libjasper-dev libjpeg8-dev gettext liblcms2-dev` on Bullseye returns:

```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package libjpeg8-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libjpeg9-dev libjpeg62-turbo-dev

E: Package 'libjpeg8-dev' has no installation candidate
```

Installing libjpeg9-dev via:

`sudo apt-get install libjasper-dev libjpeg9-dev gettext liblcms2-dev`

And then running `./buildme` produces:

`/usr/bin/ld: warning: libjpeg.so.62, needed by /usr/lib/gcc/arm-linux-gnueabihf/10/../../../arm-linux-gnueabihf/libjasper.so, may conflict with libjpeg.so.9`

I purged `libjpeg9-dev` and installed `libjpeg62-turbo-dev` and the warning didn't pop up and the build seemed to succeed.

**Comment by kyleboddy** [comment]
Feel free to close, just wanted to note it for those who come here via `raspiraw`.

**Comment by 6by9** [comment]
Thanks for the report.
README updated for Bullseye, and buildme gained the -DNODEPS flag to get around the linker issue.
